package vista;


import Logica.Simulacion;
import Logica.Usuario;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * gui.java
 *
 * Created on 6/03/2011, 02:43:24 PM
 */


public class gui extends javax.swing.JFrame {
    Point p = new Point(-20, -20);
    boolean estado=true;
    int contador=0;
    int[] caja = {0,0,0};
    int j=14;
    ArrayList<Point> fila= new ArrayList<Point>();
    /** Creates new form gui */
    public gui() {
        initComponents();
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/2.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/2.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/2.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/2.png"))); // NOI18N

        jButton5.setText("Iniciar simulacion");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/3.png"))); // NOI18N

        jLabel3.setText("Tiempo total de las cajas : ");

        jLabel8.setText("Informe:");

        jLabel9.setText("Tiempro promedio de usuarios en cajas:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(751, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(192, 192, 192))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(983, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7))
                            .addGap(65, 65, 65)
                            .addComponent(jLabel1)
                            .addContainerGap())
                        .addComponent(jLabel9))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jButton5)
                .addContainerGap(883, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(154, 154, 154))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(jLabel9)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(105, 105, 105)
                .addComponent(jButton5)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Thread t = new Thread(){
            @Override
            public void run(){
                Simulacion m = new Simulacion();
                m.simular();
            }
        };
        t.start();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    @Override
    public void paint(Graphics g){
        super.paint(g);
        g.setColor(Color.red);
        for (int i = 0; i < fila.size(); i++) {
            g.fillOval(fila.get(i).x,fila.get(i).y, 40, 40);
           // System.out.println(fila.get(i)+" "+i);
        }
        for(int i=0;i<3;i++){
            if(caja[i]==1){
                if(i==0){
                    g.fillOval(870,120, 40, 40);
                }else if(i==1){
                    g.fillOval(870,220, 40, 40);
                }else{
                    g.fillOval(870,315, 40, 40);
                }
            }
        }

       g.setColor(Color.black);
       g.fillOval(p.x, p.y, 40, 40);

    }
    public void pintar(Usuario[] fila , Usuario[] caja){
        //for
    }
    
    public void animarEntrada(){
        Thread t= new Thread(){
            @Override
            public void run(){
                int x=305;
                Point aux=new Point(x, 220);
                fila.add(aux);
                contador=contador+1;
                int n=contador;
                repaint();
                int num=j;
                j=j-1;
                for(int i=0; i<num;i++){
                    aux=new Point(x, 220);
                   fila.set(n-1, aux);
                   repaint();
                   x=x+40;
                       try {
                        sleep(10);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }

            }
        };
        t.start();
    }
    public void deFilaACaja(){
        Thread t= new Thread(){
            @Override
            public void run(){
                int c=0;
                repaint();
                for(int i=0; i<3;i++){
                   if(caja[i]==0&&fila.size()!=0){
                       fila.remove(0);
                       c=c+1;
                       caja[i]=1;
                       j=j+1;
                       contador=contador-1;
                       repaint();
                        try {
                            sleep(100);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
                        }
                   }
                }
                acomodar(c);

            }
        };
        t.start();
        repaint();
    }
    public void acomodar(final int n){
        Thread t= new Thread(){
            @Override
            public void run(){
                for(int i=0;i<fila.size();i++){
                    Point aux=fila.get(i);

                    for(int j = 0;j<n;j++){
                        aux = new Point(aux.x+40,aux.y);
                        fila.set(i, aux);
                        repaint();
                        try {
                            sleep(10);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
        };
        t.start();
    }
    public void sacar(final int pos){
        estado=false;
        caja[pos]=0;
        Thread t= new Thread(){
            @Override
            public void run(){
                if(pos==0){
                    int y=75;
                    while(y>-30){
                        p=new Point(860, y);
                        y=y-40;
                        repaint();
                        try {
                            sleep(100);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    estado= true;
                }else if(pos==1){
                    int y=180;
                    while(y>-30){
                        p=new Point(860, y);
                        y=y-40;
                        repaint();
                        try {
                            sleep(100);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    estado= true;
                }else if(pos==2){
                    int y=275;
                    while(y>-30){
                        p=new Point(860, y);
                        y=y-40;
                        repaint();
                        try {
                            sleep(100);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    estado= true;
                }
            }
        };
        t.start();
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }
    public JLabel getjLabel9() {
        return jLabel9;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
