/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelSevenEleven.java
 *
 * Created on 26/09/2011, 10:27:21 AM
 */

/*
 * Autores:
 * Luis Alfonso Velez Santos
 * Carlos Yesid Hernandez Herrera
 * Jose Esteban Betin Diaz
 */

package Vista;

import auxiliares.Auxiliares;
import auxiliares.LimitadorSoloNumerosNumMaxCaracteres;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import simulaciones.SimulacionEjercicio10;
import simulaciones.SimulacionEjercicio11;
import simulaciones.SimulacionEjercicio4;
import simulaciones.SimulacionSevenEleven;

/**
 *
 * @author warlock
 */
public class JPanelEjercicio11 extends javax.swing.JPanel {
    ArrayList<Float> numeros1;
    ArrayList<Float> numeros2;
    SimulacionEjercicio11 e ;
    private int velocidad;
    /** Creates new form JPanelSevenEleven */
    public JPanelEjercicio11() {
        initComponents();
        cambiarVelocidad();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSimular = new javax.swing.JButton();
        jCheckBoxRapido = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldValorMaximoAEvaluar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPaneResultado = new javax.swing.JScrollPane();
        jTextAreaResultado = new javax.swing.JTextArea();
        jProgressBar1 = new javax.swing.JProgressBar();

        setLayout(null);

        jButtonSimular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/iconos/1317344174_play.png"))); // NOI18N
        jButtonSimular.setToolTipText("Simular");
        jButtonSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimularActionPerformed(evt);
            }
        });

        jCheckBoxRapido.setText("Rapido");
        jCheckBoxRapido.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxRapidoStateChanged(evt);
            }
        });

        jLabel2.setText("Valor Maximo a Evaluar");

        jTextFieldValorMaximoAEvaluar.setDocument(new LimitadorSoloNumerosNumMaxCaracteres(jTextFieldValorMaximoAEvaluar, 10));
        jTextFieldValorMaximoAEvaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorMaximoAEvaluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldValorMaximoAEvaluar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jButtonSimular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBoxRapido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValorMaximoAEvaluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(jCheckBoxRapido)
                .addGap(18, 18, 18)
                .addComponent(jButtonSimular))
        );

        add(jPanel1);
        jPanel1.setBounds(327, 121, 430, 290);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ejercicio 11");
        add(jLabel1);
        jLabel1.setBounds(12, 12, 870, 37);

        jScrollPane1.setViewportView(jList1);

        jScrollPane2.setViewportView(jList2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/iconos/1317343951_project-open.png"))); // NOI18N
        jButton1.setToolTipText("Importar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/iconos/1317343951_project-open.png"))); // NOI18N
        jButton2.setToolTipText("Importar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                        .addGap(194, 194, 194))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jScrollPane1, jScrollPane2});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel2);
        jPanel2.setBounds(12, 55, 297, 356);

        jTextAreaResultado.setColumns(20);
        jTextAreaResultado.setRows(5);
        jScrollPaneResultado.setViewportView(jTextAreaResultado);

        jProgressBar1.setString("Simular");
        jProgressBar1.setStringPainted(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPaneResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPaneResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        add(jPanel3);
        jPanel3.setBounds(0, 429, 770, 194);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser jf = new JFileChooser();
        jf.setMultiSelectionEnabled(false);
        int r =jf.showOpenDialog(jf);
        if(r == JFileChooser.APPROVE_OPTION){
            ObjectInputStream entrada;
            try {
                entrada = new ObjectInputStream(new FileInputStream(jf.getSelectedFile()));
                numeros1 = (ArrayList<Float>) entrada.readObject();
                System.out.println(numeros1.size());
                if(!numeros1.isEmpty()){
                 
                    DefaultListModel lm = new DefaultListModel();

                    for(int i=0;i<numeros1.size();i++){
                        lm.addElement((i+1)+": "+numeros1.get(i));

                    }
                    jList1.setModel(lm);
                    JOptionPane.showMessageDialog(null, "Lista de números importado con éxito");                  
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al importar el archivo");
            }


        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser jf = new JFileChooser();
        jf.setMultiSelectionEnabled(false);
        int r =jf.showOpenDialog(jf);
        if(r == JFileChooser.APPROVE_OPTION){
            ObjectInputStream entrada;
            try {
                entrada = new ObjectInputStream(new FileInputStream(jf.getSelectedFile()));
                numeros2 = (ArrayList<Float>) entrada.readObject();
                System.out.println(numeros2.size());
                if(!numeros2.isEmpty()){
//                    
                    DefaultListModel lm = new DefaultListModel();
                    jList2.setModel(lm);
                    for(int i=0;i<numeros2.size();i++){
                        lm.addElement((i+1)+": "+numeros2.get(i));
                    }
                    jList2.setModel(lm);
                    JOptionPane.showMessageDialog(null, "Lista de números importado con éxito");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al importar el archivo");
            }


        }
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimularActionPerformed
    if(numeros1!=null&&numeros2!=null &&!jTextFieldValorMaximoAEvaluar.getText().equalsIgnoreCase("")){
       jTextAreaResultado.setText("");
       e = new SimulacionEjercicio11();
       e.setNumeros1(numeros1);
       e.setNumeros2(numeros2);
       e.setValorMaximoAEvaluar(Auxiliares.convertirStringAEntero(jTextFieldValorMaximoAEvaluar)); 
       e.setListaResultados(jTextAreaResultado);
       e.setBoton(jButtonSimular);
       e.setjScrollPaneResultado(jScrollPaneResultado);
       e.setJp(jProgressBar1);
       e.setVelocidad(velocidad);
       e.start();

        }else{
            JOptionPane.showMessageDialog(this, "Hay campos vacios");
        }

    }//GEN-LAST:event_jButtonSimularActionPerformed

    private void jCheckBoxRapidoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxRapidoStateChanged
        cambiarVelocidad();
}//GEN-LAST:event_jCheckBoxRapidoStateChanged

    private void jTextFieldValorMaximoAEvaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorMaximoAEvaluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorMaximoAEvaluarActionPerformed

 private void cambiarVelocidad(){
        if(jCheckBoxRapido.isSelected()){
                velocidad=0;
            }else{
                velocidad=100;
            }
         if(e!=null){
            if(jCheckBoxRapido.isSelected()){
                e.setVelocidad(0);
            }else{
                e.setVelocidad(100);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonSimular;
    private javax.swing.JCheckBox jCheckBoxRapido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneResultado;
    private javax.swing.JTextArea jTextAreaResultado;
    private javax.swing.JTextField jTextFieldValorMaximoAEvaluar;
    // End of variables declaration//GEN-END:variables


  


}
