/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelSimulacionInventario.java
 *
 * Created on 1/09/2011, 11:37:08 PM
 */

 /*
 * Autores:
 * Luis Alfonso Velez Santos
 * Carlos Yesid Hernandez Herrera
 * Jose Esteban Betin Diaz
 */

package Vista;

import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import simulaciones.SimulacionInventario;
import auxiliares.LimitadorSoloNumerosNumMaxCaracteres;
import simulaciones.SimulacionEjercicio6;

/**
 *
 * @author warlock
 */
public class JPanelSimulacionesEjercicios_6 extends javax.swing.JPanel {
    ArrayList<Float> numeros1;
    ArrayList<Float> numeros2;
    private int velocidad;
    SimulacionEjercicio6 sim;
    /** Creates new form JPanelSimulacionInventario */
    public JPanelSimulacionesEjercicios_6() {
        initComponents();
        cambiarVelocidad();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPaneCorridas = new javax.swing.JScrollPane();
        jTextAreaCorridas = new javax.swing.JTextArea();
        jScrollPaneResultados = new javax.swing.JScrollPane();
        jTextAreaResultados = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jCheckBoxRapido = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCorridas = new javax.swing.JTextField();
        jButtonSimular = new javax.swing.JButton();

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/iconos/1317343951_project-open.png"))); // NOI18N
        jButton1.setToolTipText("Importar");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jLabel2.setText("Corridas");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Inventario");

        jProgressBar1.setString("Simular");
        jProgressBar1.setStringPainted(true);

        jTextAreaCorridas.setColumns(20);
        jTextAreaCorridas.setRows(5);
        jScrollPaneCorridas.setViewportView(jTextAreaCorridas);

        jTextAreaResultados.setColumns(20);
        jTextAreaResultados.setRows(5);
        jTextAreaResultados.setToolTipText("Resultados");
        jScrollPaneResultados.setViewportView(jTextAreaResultados);

        jCheckBoxRapido.setText("Rapido");
        jCheckBoxRapido.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxRapidoStateChanged(evt);
            }
        });

        jLabel3.setText("Numero de Corridas");

        jTextFieldCorridas.setDocument(new LimitadorSoloNumerosNumMaxCaracteres(jTextFieldCorridas, 6));

        jButtonSimular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/iconos/1317344174_play.png"))); // NOI18N
        jButtonSimular.setBorderPainted(false);
        jButtonSimular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(jTextFieldCorridas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBoxRapido, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSimular, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCorridas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxRapido)
                .addGap(82, 82, 82)
                .addComponent(jButtonSimular)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPaneCorridas, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jScrollPane1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPaneCorridas, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser jf = new JFileChooser();
        
        jf.setMultiSelectionEnabled(false);
        int r =jf.showOpenDialog(jf);
        if(r == JFileChooser.APPROVE_OPTION){
             ObjectInputStream entrada;
            try {
                entrada = new ObjectInputStream(new FileInputStream(jf.getSelectedFile()));
                numeros1 = (ArrayList<Float>) entrada.readObject();
                System.out.println(numeros1.size());
                if(!numeros1.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Lista de números importado con éxito");
                    DefaultListModel lm = new DefaultListModel();
                    jList1.setModel(lm);
                    for(int i=0;i<numeros1.size();i++){
                        lm.addElement((i+1)+": "+numeros1.get(i));
                    }
                    jList1.setModel(lm);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al importar el archivo");
            }


        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimularActionPerformed
        
        if(!jTextFieldCorridas.getText().equalsIgnoreCase("")&&numeros1!=null){
            jTextAreaCorridas.setText("");
            jTextAreaResultados.setText("");
            sim = new  SimulacionEjercicio6();
            sim.setjScrollPaneResultado(jScrollPaneResultados);
            sim.setjScrollPaneCorridas(jScrollPaneCorridas);
            sim.setJp(jProgressBar1);
            sim.setNumeros1(numeros1);
            sim.setCorridas(auxiliares.Auxiliares.convertirStringAEntero(jTextFieldCorridas)); 
            sim.setListaResultados(jTextAreaResultados) ;
            sim.setBoton(jButtonSimular);
            sim.setListaCorridas(jTextAreaCorridas) ;
            sim.setVelocidad(velocidad);

            sim.start();
//            float aux1=((float)sim.getAcum30()/sim.getNumCorridas())*100;
//            float aux2=((float)sim.getAcum8()/sim.getNumCorridas())*100;
//            String economica;
//            if(sim.getAcum30()>sim.getAcum8()){
//                economica="Es mas economica la compra cada 8 dias";
//            }else{
//                economica="Es mas economica la compra cada 30 articulos";
//            }
//            jTextArea1.setText("Resultados\n\nPara cada 30 Articulos el numero\nde veces"
//                    + "que fue mayor es: "+sim.getAcum30()+
//                    "\nPara cada 8 dias el numero\nde veces que fue mayor es: "+sim.getAcum8()+""
//                    + "\nEl porcentaje para 30 articulos es:"+aux1+"%\n"
//                    + "El porcetaje para 8 dias es: "+aux2+"%" +"\n"+economica);
//            DefaultListModel lm = new DefaultListModel();
//            jList3.setModel(lm);
//            ArrayList<String> cojPanelEjercicio6r = sim.getCorridas();
//            for(int i=0;i<cor.size();i++){
//                 lm.addElement(cor.get(i));
//             }
//            jList3.setModel(lm);

        }else{
            JOptionPane.showMessageDialog(null, "Hay campos vacios");
        }

    }//GEN-LAST:event_jButtonSimularActionPerformed

    private void jCheckBoxRapidoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxRapidoStateChanged
        cambiarVelocidad();
}//GEN-LAST:event_jCheckBoxRapidoStateChanged

    private void cambiarVelocidad(){
        if(jCheckBoxRapido.isSelected()){
                velocidad=0;
            }else{
                velocidad=100;
            }
         if(sim!=null){
            if(jCheckBoxRapido.isSelected()){
                sim.setVelocidad(0);
            }else{
                sim.setVelocidad(100);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSimular;
    private javax.swing.JCheckBox jCheckBoxRapido;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneCorridas;
    private javax.swing.JScrollPane jScrollPaneResultados;
    private javax.swing.JTextArea jTextAreaCorridas;
    private javax.swing.JTextArea jTextAreaResultados;
    private javax.swing.JTextField jTextFieldCorridas;
    // End of variables declaration//GEN-END:variables

}
